#ifndef WBCFFADAPTOR_GLOBAL_H
#define WBCFFADAPTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WBCFFADAPTOR_LIBRARY)
#  define WBCFFADAPTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WBCFFADAPTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WBCFFADAPTOR_GLOBAL_H
